In [17]:
#1. Write a Python Program to Add Two Matrices?

import numpy as np

mat1 = np.array([[1,1,1],[1,1,1],[1,1,1]])
mat2 = np.array([[2,2,2],[2,2,2],[2,2,2]])
mat3 = np.array([[3,3,3],[3,3,3],[3,3,3]])
mat4 = np.array([[12,5,3],[15,2,9],[4,33,98]])

In [18]:
def added(x,y):
    """Python program to add two matrices"""
    return x+y

added(mat1,mat2)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [35]:
#2. Write a Python Program to Multiply Two Matrices?
def mul(x,y):
    """Multiplying two matrices"""
    try:
        return x*y
    except:
        return "False info by user"

mul(mat3,mat2)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [21]:
#3. Write a Python Program to Transpose a Matrix?

def transposer(x):
    """Returning transpose"""
    return x.transpose()

transposer(mat4)

array([[12, 15,  4],
       [ 5,  2, 33],
       [ 3,  9, 98]])

In [42]:
#4. Write a Python Program to Sort Words in Alphabetic Order?

def sorter(x):
    """Sorting words"""
    try:
        vals = list(x)
        vals.sort()
        main = ""
        for i in vals:
            main += i
        return main
    except:
        return "Provide string"
    

In [44]:
sorter("cba")

'abc'

In [45]:
sorter(123)

'Provide string'

In [66]:
#5. Write a Python Program to Remove Punctuation From a String?
def remover(x):
    """Removing punctuation"""
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    try:
        out = '' 
        for i in x:
            if i in punctuations:
                x = x.replace(i, "")
        return x
            
    except Exception as e:
        return "Provide string",e
        

In [67]:
remover("""Ashu!()-[]{};:'"\,<>./?@#$%^&*_~""")

'Ashu'